<?php $thisPage="About Us"; ?>
<!DOCTYPE HTML>
<HTML>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Learn more about why Metrics Fitness Lab believes in a scientific approach to fitness.">
    <meta name="author" content="">

    <title>Metrics Fitness Lab, Auburn AL</title>

    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="manifest.json">
    <link rel="mask-icon" href="safari-pinned-tab.svg" color="#4e9ab0">
    <meta name="theme-color" content="#ffffff">


    <!--build:css css/main.min.css-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">

    <link rel="stylesheet" href="bower_components/normalize-css/normalize.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/about-us.css" type="text/css">
    <!--endbuild-->

  </head>
  <body>

    <?php include("nav.phtml") ?>

    <section>
      <h1>About Us</h1>
      <div class="container-fluid">
        <div class="row text-center">
          <div class="col-lg-5 col-md-5 col-sm-12 text-center">
            <img class="image" src="img/about-us.png"/>
          </div>
          <div class="col-lg-7 col-md-7 col-sm-12 content-container">
            <p class="content">
              Metrics Fitness Lab is a total health center, focusing on meeting our clients’ personal health
              and fitness goals while fostering a safe diet and exercise routine. We are more than just a team
              of personal trainers – We are dietitians, team leaders and motivators who change each workout to
              meet clients where ever they are in their fitness journey. Hard work in the gym and your kitchen
              needs to be measured and monitored, which is why we track your progress through a variety of metrics.
              We not only weigh our clients, but also measure them in nine parts of their body and track their body
              fat percentage every six weeks, which gives more valuable information than the number on the scale.
              Whether your goal is to lose or gain weight, tone your body or simply feel better in your daily life,
              our team of trainers, dietitians, and health and fitness consultants will guide you to becoming your
              best self.
            </p>
          </div>
        </div>
      </div>
    </section>

    <?php include("footer.phtml"); ?>

    <!--build:js /js/main.min.js -->
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="js/about-us.js"></script>
    <!-- endbuild -->
  </body>

</HTML>
