<?php $thisPage="Blog"; ?>
<!DOCTYPE HTML>
<HTML>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Follow our blog to learn more about what we believe in at Metrics Fitness Lab!">
    <meta name="author" content="">

    <title>Metrics Fitness Lab, Auburn AL</title>

    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="manifest.json">
    <link rel="mask-icon" href="safari-pinned-tab.svg" color="#4e9ab0">
    <meta name="theme-color" content="#ffffff">

    <!--build:css css/main.min.css-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">

    <link rel="stylesheet" href="bower_components/normalize-css/normalize.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/blog.css" type="text/css">
    <!--endbuild-->

  </head>
  <body>

    <?php include("nav.phtml"); ?>

    <section>
      <h1>Blog</h1>
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <ul class="list-group menu-items">
              <?php
                foreach($data['blogs'] as $blog):
               ?>
              <li class="list-group-item">
                <div class="row">
                  <div class="col-lg-3 col-md-3 col-sm-3 vcenter">
                      <img src="<?= $blog->getPictureUrl() ?>">
                  </div><!--
                  --><div class="col-lg-9 col-md-9 col-sm-9 vcenter">
                    <a href="<?=$router->pathFor('blog-detail', ['id' => $blog->getId()])?>"><h3><?= $blog->getTitle() ?></h3></a>
                    <h6><em>By <?= $blog->getUsername() ?></em>   |   <?= $blog->getDate() ?></h6>
                    <p><?= $blog->getShortContent() ?></p>
                  </div>
                </div>
              </li>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
      </div>
    </section>

  <?php include("footer.phtml"); ?>

  <!--build:js /js/main.min.js -->
  <script src="bower_components/jquery/dist/jquery.min.js"></script>
  <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="js/blog.js"></script>
  <!-- endbuild -->
</body>

</HTML>
