<?php $thisPage="Calendar"; ?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Stay up-to-date with events happening at Metrics Fitness Lab and in the Auburn/Opelika community.">
  <meta name="author" content="">

  <title>Calendar of Events | Metrics Fitness Lab, Auburn AL</title>

  <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
  <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="manifest.json">
  <link rel="mask-icon" href="safari-pinned-tab.svg" color="#4e9ab0">
  <meta name="theme-color" content="#ffffff">

  <link rel="stylesheet" href="bower_components/normalize-css/normalize.css">
  <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="bower_components/fullcalendar/dist/fullcalendar.min.css" />
  <link rel="stylesheet" href="css/calendar.css" type="text/css">

</head>

<body>
  <?php include("nav.phtml"); ?>

  <!-- We will attach the calendar to this element -->
  <section>
    <h1>Calendar</h1>
    <p>
      Stay up-to-date with events at Metrics, our partners’, and our community here! Make sure to check in regularly, as we are always adding to our calendar. Have an event we should know about! Shoot us an email at Info@metricsfitnesslab.com
    </p>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 calendar-col">
          <div id="calendar"></div>
        </div>
      </div>
    </div>
  </section>

  <?php include("footer.phtml"); ?>

  <div id="fullCalModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
          <h1 id="modalTitle" class="modal-title"></h1>
        </div>
        <div id="modalBody" class="modal-body">
          <h4 id="modalStartTime"></h4>
          <h4 id="modalEndTime"></h4>
          <h4 id="modalDescription" style="margin-top: 1em;font-size: 26px;font-weight: 300;"></h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <!-- <button class="btn btn-primary"><a id="eventUrl" target="_blank">Event Page</a></button> -->
        </div>
      </div>
    </div>
  </div>

  <script src="bower_components/jquery/dist/jquery.min.js"></script>
  <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="bower_components/moment/min/moment.min.js"></script>
  <script src="bower_components/fullcalendar/dist/fullcalendar.min.js"></script>
  <script>
  (function($) {
    $('#calendar').fullCalendar({
      events: 'api',
      eventDataTransform: function(rawEventData) {
        return {
          id: rawEventData.id,
          title: rawEventData.title,
          description: rawEventData.description,
          start: rawEventData.start,
          end: rawEventData.end,
          url: rawEventData.url,
          allDay: false
        };
      },
      header: {
        left:   'prev,next today',
        center: 'title',
        right:  'month,agendaWeek,agendaDay'
      },
      eventRender: function(event, element) {
        $(element).tooltip({title: event.description});
      },
      eventClick:  function(event, jsEvent, view) {
        $('#modalTitle').html(event.title);
        $('#modalDescription').html(event.description);
        $('#modalStartTime').html("Start - " + moment(event.start).format("dddd, MMMM Do YYYY, h:mm a"));
        $('#modalEndTime').html("End - " + moment(event.end).format("dddd, MMMM Do YYYY, h:mm a"));
        $('#eventUrl').attr('href',event.url);
        $('#fullCalModal').modal();
      },
      aspectRatio: 1
    });
  })(jQuery);
  </script>
</body>

</html>
