<?php $thisPage="Crew"; ?>
<!DOCTYPE HTML>
<HTML>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Meet or team of registered trainers and health professionals that work at Metrics Fitness Lab.">
    <meta name="author" content="">

    <title>Metrics Fitness Lab, Auburn AL</title>

    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="manifest.json">
    <link rel="mask-icon" href="safari-pinned-tab.svg" color="#4e9ab0">
    <meta name="theme-color" content="#ffffff">

    <!--build:css css/main.min.css-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">

    <link rel="stylesheet" href="bower_components/normalize-css/normalize.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/crew.css" type="text/css">
    <!--endbuild-->

  </head>
  <body>

    <?php include("nav.phtml"); ?>

    <section>
      <h1>Metrics Crew</h1>
      <div class="container-fluid">
        <div class="row gutter-20">
          <div class="col-lg-4 text-center crew">
            <img class="img-circle" src="img/crew-page-chappy-headshot.png"/>
            <h5>Chappy Chapman</h5>
            <p>
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
            </p>
          </div>
          <div class="col-lg-4 text-center crew">
            <img class="img-circle" src="img/crew-page-ike-headshot.png"/>
            <h5>Ike Stephens</h5>
            <p>
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
            </p>
          </div>
          <div class="col-lg-4 text-center crew">
            <img class="img-circle" src="img/crew-page-natalie-headshot.png"/>
            <h5>Ike Stephens</h5>
            <p>
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
              Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum. Lorem Ipsum.
            </p>
          </div>
        </div>
        <!-- <h1 id="join-crew">Join the Crew</h1>
        <div class="row">
          <div class="col-lg-9">
            <p class="join-crew-text">
              Our Metrics Fitness Lab team is always accepting applications for certified personal trainers
               to join our team. If you are a highly motivated person who has a passion for health and fitness,
                please send your resume and application to <a href="mailto:chappy@metricsfitnesslab.com">chappy@metricsfitnesslab.com</a>
            </p>
          </div>
          <div class="col-lg-3">
            <img class="img-responsive" src="http://placehold.it/350x150" />
          </div>
        </div> -->
      </div>
    </section>

    <?php include("footer.phtml"); ?>

    <!--build:js /js/main.min.js -->
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="js/crew.js"></script>
    <!-- endbuild -->
  </body>

</HTML>
