<?php $thisPage="FAQ"; ?>
<!DOCTYPE HTML>
<HTML>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Have questions about small group training or personal training? Look no further.">
    <meta name="author" content="">

    <title>Metrics Fitness Lab, Auburn AL</title>

    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="manifest.json">
    <link rel="mask-icon" href="safari-pinned-tab.svg" color="#4e9ab0">
    <meta name="theme-color" content="#ffffff">

    <!--build:css css/main.min.css-->
    <link rel="stylesheet" href="bower_components/normalize-css/normalize.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/faq.css" type="text/css">
    <!--endbuild-->

  </head>
  <body>

    <?php include("nav.phtml") ?>
    <section>
      <div class="container-fluid text-center">
        <div class="row">
          <div class="col-lg-12">
            <h1>Frequently Asked Questions</h1>
            <img src="img/faq-first-pic.png" alt="FAQ Picture" id="faq-first-pic"/>
            <img src="img/faq-changing-culture-title.png" style="margin-top: 30px;" id="faq-changing-culture-title"/>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <h4 style="margin-top: 30px;">Why is it called Metrics Fitness Lab?</h4>
            <p>
              The reason it is called Metrics Fitness Lab is because there are many other factors that are incorporated
              into fitness besides just losing weight. Our mission statement is “Changing the Culture of Fitness.” We do
              this through education and a science and research based system (Lab). Many people lose the weight they want
              to lose, only to see it return again. We strive to teach you how to live and maintain a healthy way of living.
              Our “Methods” or stations throughout the 1 hour workout target various aspects of fitness, from cardio, strength
              training, stretching, mobility, recovery, as well as other “Metrics” of fitness.
            </p>
          </div>
        </div>
        <hr />

        <div class="row">
          <div class="col-lg-3 vcenter">
            <img class="img-responsive" src="img/faq-phone.png" alt="The Official Metrics App" id="faq-phone"/>
          </div><!--
          --><div class="col-lg-9 vcenter" id="interested-class">
            <h4 style="text-align: left">I’m interested in trying a class, how do I get started?</h4>
            <p>
              You can download our app, Metrics Fitness Lab, from the app store and register
              yourself for one of our classes. You are also welcome to drop in to one of our classes,
              we just ask that you come about 15 minutes early so we can give you a brief orientation
              and get your heartrate monitor set up. Feel free to contact us at 334 740 6442 to set up
              a class.
            </p>
            <img class="img-responsive" style="text-align: left" src="img/available-in-app-store.png" alt="Our app is available in the App Store" id="available-in-app-store"/>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-12">
            <h4>What is your class schedule?</h4>
            <p class="class-schedule-paragraph">
              Currently our class schedule is Monday through Friday
              <br/>
              6am, 8:30am, 11am, 4pm, 5pm, and 7pm (no 7pm class on Fridays)
            </p>
            <img src="img/class-schedule-chart.png" id="class-schedule-chart" />
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-12">
            <h4>How does Metrics differ from other group training classes?</h4>
            <p>
              We feel you can go anywhere and get instruction on picking up and moving weight around. Most group
              classes have “fitness instructors” and that’s exactly what they do is instruct. But ask yourself these
              questions: Are you doing it correctly? Are you being trained to your specific abilities, goals, and creating
              functional patterns that help you in daily life? Are you being challenged on your mobility, range of
              motion, flexibility, creating a better posture and endurance? Are you being educated on the science
              behind the movements, your metabolism, and how your body works as a system? Sure, an instructor
              can tell you how long to run on cardio equipment or how many sets of weight to move in what direction
              but how is your form? Each class at Metrics Fitness Lab is taught by a personal trainer who customizes
              the program and workout to your specific needs and answers yes to all these questions. This
              customization goes beyond the time that you are with us but also ways to fit fitness into your daily life.
              Classes are small and we keep a high ratio of trainers to clients to ensure you still get the individual
              attention that you may need. We also take the time to get to know each individual person throughout
              the workout and encourage a family atmosphere. Each class has a 30 minute post class time built in so
              the staff can take a little extra time to get to know everyone as well as time for those who want to stay
              after and to talk with friends or make new ones. We also use this time to take measurements to track
              progress. We are not crossfit or affiliated with crossfit in any way.
            </p>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-12">
            <h4>Do I really need the heartrate monitor or can I bring my own?</h4>
            <p>
              At Metrics Fitness Lab, we require that you use a Myzone heart rate monitor. If you already have a
              Myzone heart rate monitor then you can use it. Other devices are not as specific and accurate as the
              Myzone nor do they sync up with our system. Our system is specifically designed for trainers to use to
              maximize your individual training effort, to maximize efficiency in your workout, as a method of
              accountability, as a tool for learning how to train properly, and our workouts are designed around a
              point system giving you a goal to strive for. The belt is because it calibrates to you specifically and adapts
              as you change through your fitness journey.
            </p>
            <img class="img-responsive" src="img/myzone-watch.png" style="margin: auto;" id="myzone-watch"/>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-3 vcenter">
            <img class="img-responsive" src="img/faq-injury-graphic.png" id="faq-injury-graphic" style="margin-bottom: 2em" />
          </div><!--
          --><div class="col-lg-9 vcenter" id="injury">
            <h4>If I have an injury or something that limits my ability to workout, can I still participate in a group class?</h4>
            <p>
              Yes. Everyone at Metrics Fitness Lab is a certified personal trainer and is able to adjust and modify
              workouts as needed to still be effective and target specific muscle groups.
            </p>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-12">
            <img class="img-responsive" src="img/faq-expect-door.png" id="expect-pic"/>
            <h4>What do I expect when I walk in the door?</h4>
            <p>
              Metrics Fitness Lab is a fitness studio workout facility with group personal training classes offered
              throughout the day. The workouts are based in 4 different stations, or “methods” that are all designed
              to take a holistic approach to fitness. We use the latest in heartrate monitoring technology to measure
              the amount of effort to put forth in your workouts. The workouts are designed on a point based system
              allowing you to move at your own pace.
            </p>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-5 vcenter">
            <img src="img/faq-new-to-working-out.png" id="new-to-working-out"/>
          </div><!--
          --><div class="col-lg-7 vcenter" id="new-working-out">
            <h4>I’m new to working out and I’m not sure if group is best for me...</h4>
            <p>
              We strive to create a non-intimidating environment. That’s why we keep the groups small and personal.
              Everyone here from the staff to those working out is very encouraging. We are here for those who want
              to work out but are not sure what to do or how to get started. We also have one on one personal
              training options available.
            </p>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-12">
            <h4>Are these classes for experienced or someone who is just starting?</h4>
            <p>
              Our workouts are designed to accommodate all fitness levels, ages, and abilities. The workouts are
              mostly functional body weight movements designed to help you move better through your life. We have
              worked with people who have never worked out before to those training for half and whole marathons,
              and Ironman triathletes.
            </p>
          </div>
        </div>
        <hr />
        <div class="bunch-o-questions">
          <div class="row text-center">
            <div class="col-md-5 col-md-offset-1">
              <h4>What age range do you offer services for?</h4>
              <p>
                We work with individuals of all age ranges.
              </p>
            </div>
            <div class="col-md-5">
              <h4>What and when should I eat?</h4>
              <p>
                A light meal or snack an hour an before working out.
              </p>
            </div>
          </div>
          <div class="row text-center">
            <div class="col-md-5 col-md-offset-1">
              <h4>What should I wear?</h4>
              <p>
                Wear attire that you feel comfortable working out in, shoes that are supportive and able to run
                in, and if you would like bring a bottle of water.
              </p>
            </div>
            <div class="col-md-5">
              <h4>How long are your contracts?</h4>
              <p>
                We do month to month and ask for a 30 day notice for cancellations.
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <h4 style="margin-top: 1em;">How many classes should I attend per week to reach my goals?</h4>
            <p>
              That depends on you as an individual. For some people this is their primary method of working out and
              they come often. For others, this is a supplement to their usual workout, like swimmers. Many find
              coming 3 times a week to be optimal.
            </p>
          </div>
        </div>
        <hr />
        <div class="row">
          <div class="col-lg-12">
            <img src="img/faq-expect-results.png" id="faq-expect-results"/>
            <h4>What can I expect my results to be?</h4>
            <p>
              We focus on lost body fat percentage and inches more than the scale. We feel these 2 things are a more
              accurate representation than what the scale shows as it relates to fitness. For example you can use the
              restroom and lose weight but that mean that you are in better shape? On average our members lose
              about 2.5 to 3 percent body fat per six weeks.
            </p>
          </div>
        </div>
      </div>
    </section>

    <?php include("footer.phtml"); ?>

    <!--build:js /js/main.min.js -->
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- endbuild -->
  </body>

</HTML>
