<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?= "{$router->pathFor('home')}"; ?>"><img src="http://localhost/MetricFitnessLabWebsite/img/logo.png" alt="Metrics Fitness Lab Logo"/></a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li <?php if ($thisPage=="Home")
echo " id=\"currentpage\""; ?>><a href="<?= "{$router->pathFor('home')}"; ?>">Home</a></li>
        <li <?php if ($thisPage=="About Us")
echo " id=\"currentpage\""; ?>><a href="<?= "{$router->pathFor('about')}"; ?>">About Us</a></li>
        <li <?php if ($thisPage=="Blog")
echo " id=\"currentpage\""; ?>><a href="<?= "{$router->pathFor('blog')}"; ?>">Blog</a></li>
        <li <?php if ($thisPage=="Calendar")
echo " id=\"currentpage\""; ?>><a href="<?= "{$router->pathFor('calendar')}"; ?>">Calendar</a></li>
        <li <?php if ($thisPage=="Crew")
echo " id=\"currentpage\""; ?>><a href="<?= "{$router->pathFor('crew')}"; ?>">Meet the Team</a></li>
        <li <?php if ($thisPage=="FAQ")
echo " id=\"currentpage\""; ?>><a href="<?= "{$router->pathFor('faq')}"; ?>">FAQ</a></li>
        <li id="sign-up"><a href="<?= "{$router->pathFor('signup')}"; ?>">Sign Up<br /> <span id="today">Today</span></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
