<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>New Testimonial</title>

  <link rel="stylesheet" href="../../bower_components/normalize-css/normalize.css">
  <link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="../../css/new-testimonial.css" type="text/css">
</head>

<body>

  <section>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1>New Testimonial</h1>
          <form method="post" action="">
            <div class="form-group">
              <label for="author_name">Name of Author</label>
              <input type="text" id="author_name" class="form-control" placeholder="Author name... " name="author_name">
            </div>
            <div class="form-group">
              <label for="content">Quote</label>
              <textarea type="text" class="form-control" id="content" placeholder="Testimonial content... " name="content" rows="5"></textarea>
            </div>
            <input type="submit" class="btn btn-primary" value="submit" />
          </form>
        </div>
      </div>
    </div>
  </section>

  <script src="../../bower_components/jquery/dist/jquery.min.js"></script>
  <script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>
