<!DOCTYPE HTML>
<HTML>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>New Blog</title>

    <!--build:css css/main.min.css-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">

    <link rel="stylesheet" href="../../bower_components/normalize-css/normalize.css">
    <link rel="stylesheet" href="../../bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../bower_components/bootstrap-fileinput/css/fileinput.min.css" media="all" type="text/css" />

    <!--endbuild-->

    <!--build:js /js/main.min.js -->
    <script src="../../bower_components/jquery/dist/jquery.min.js"></script>
    <script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../../bower_components/bootstrap-fileinput/js/fileinput.min.js"></script>
    <script type="text/javascript" src="../../bower_components/anchorme/src/anchorme.min.js"></script>
    <!-- endbuild -->

  </head>
  <body>


    <section>
      <h1>New Blog Post</h1>
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <form method="post" action="" enctype="multipart/form-data">
              <div class="form-group">
                <label for="blog_image">Blog Image Upload</label>
                <input type="file" class="file-loading" id="blog_image" name="blog_image" >
              </div>
              <script>
                $("#blog_image").fileinput();
              </script>

              <div class="form-group">
                <label for="title">Title of Blog Post</label>
                <input type="text" id="title" class="form-control" name="title" placeholder="Blog Post Title..">
              </div>
              <div class="form-group">
                <label for="author">Author of Blog Post</label>
                <input type="text" id="author" class="form-control" name="author" placeholder="Blog Post Author..">
              </div>
              <div class="form-group">
                <label for="content">Content of Blog Post</label>
                <textarea type="text" class="form-control" id="content" name="content" rows="10" placeholder="Blog Post Content.."></textarea>
              </div>
              <input type="submit" class="btn btn-primary" value="Create" />
            </form>
          </div>
        </div>

      </div>
    </section>

  </body>

</HTML>
