<?php $thisPage="Sign Up"; ?>
<!DOCTYPE HTML>
<HTML>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sign up for small group training or personal training classes at Metrics Fitness Lab in Auburn, Alabama!">
    <meta name="author" content="">

    <title>Metrics Fitness Lab, Auburn AL</title>

    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="manifest.json">
    <link rel="mask-icon" href="safari-pinned-tab.svg" color="#4e9ab0">
    <meta name="theme-color" content="#ffffff">

    <!--build:css css/main.min.css-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">

    <link rel="stylesheet" href="bower_components/normalize-css/normalize.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/sign-up.css" type="text/css">
    <!--endbuild-->

  </head>
  <body>

    <?php include("nav.phtml"); ?>

    <section>

      <div class="container-fluid">
        <h1>Sign Up</h1>
        <div class="row">
          <div class="col-lg-6">
            <p>
              <em>
                If you're ready for high-intensity workouts, diet accountability and a
                team of trainers and dietitians, sign up today. Read below to learn more about personal training
                and group fitness with Metrics Fitness Lab.
              </em>
            </p>
          </div>
        </div>
        <div class="row gutter-30">
          <div class="col-lg-6">
            <a href="https://clients.mindbodyonline.com/classic/ws?studioid=34382&stype=-7&sView=day&sLoc=0">
              <div class="text-center sign-up-pic group-fitness">
                <h1>Group Fitness</h1>
              </div>
            </a>
            <p>
              Metrics Fitness Lab is a fitness studio workout facility with group personal training
              classes offered throughout the day. The workouts are based in 4 different stations, or
              “methods” that are all designed to take a holistic approach to fitness. We use the latest
              in heartrate monitoring technology to measure the amount of effort to put forth in your
              workouts. The workouts are designed on a points-based system allowing you to move
              at your own pace. Our trainers are there every step of the way to adapt workouts to your
              capabilities. Classes are small to ensure personal attention from our fitness
              professionals. Those who participate in group training classes also have access to our
              registered dietitian and a personalized meal plan at no extra charge.
            </p>
          </div>
          <div class="col-lg-6">
            <a href="https://clients.mindbodyonline.com/classic/ws?studioid=34382&stype=41&sTG=4&prodId=13054">
              <div class="text-center sign-up-pic personal-training">
                <h1>Personal Training</h1>
              </div>
            </a>
            <p>
              Metrics Fitness Lab is the perfect place for a one-on- one fitness program that will hold
              you accountable, inside and outside of the gym. From solo sessions with our trainers to
              your very own personalized diet plan, you have our full attention all of the time. This
              program also incorporates a heart rate monitor and a points-based system that allows
              you to move at your own pace while also challenging yourself.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <?php include("footer.phtml"); ?>

  <!--build:js /js/main.min.js -->
  <script src="bower_components/jquery/dist/jquery.min.js"></script>
  <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="js/about-us.js"></script>
  <!-- endbuild -->
</body>

</HTML>
